# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-17 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import media_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=media_app.models.upload_location),
        ),
    ]
