# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 06:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_app', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_edit', to=settings.AUTH_USER_MODEL),
        ),
    ]
